- name: Deploy Stack
  run: |
    aws cloudformation deploy \
      --template-file infrastructure/full-stack.yml \
      --stack-name zread-full \
      --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
      --parameter-overrides \
        GitHubToken=${{ secrets.GH_TOKEN }} \
        CraftApiKey=${{ secrets.CRAFT_API_KEY }}
